from chatapp.tools.sentimentanalysis import analyze_sentiment
from chatapp.tools.websearch import web_search
from chatapp.memory.shorttermmemory import add_to_short_term_memory, add_assistant_reply_to_short_term_memory
from chatapp.memory.longtermmemory import save_memory

sentiment_tools = [analyze_sentiment,add_to_short_term_memory,save_memory]
replier_tools = [web_search, add_assistant_reply_to_short_term_memory]